<a href="https://colab.research.google.com/github/omyahro/omyahro.github.io/blob/main/RoyalsCapstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Do racial disparities persist in cancer mortality rates among women over time?**

This project explores cancer mortality trends among Black and White women across multiple decades. By analyzing long-term patterns, the goal is to identify persistent racial disparities and understand how mortality rates have changed over time.

The findings highlight differences in health outcomes, emphasizing the need for equitable healthcare access, early detection, and targeted public health interventions.

# **Problem Statement:**

Despite overall improvements in cancer treatment and prevention, racial disparities in mortality rates remain significant. Black women consistently experience higher cancer mortality rates compared to White women across decades.

Understanding how these disparities have changed over time can help identify gaps in healthcare access, treatment effectiveness, and prevention efforts, ultimately informing more equitable health policies.

## **Data Definition:**

This dataset contains age-standardized cancer mortality rates for Black and White women across multiple decades. The data is structured to allow comparison over time and between racial groups.

Key variables include:
- Year or Decade
- Race (Black, White)
- Mortality Rate (per 100,000)

The dataset enables trend analysis, comparison of mortality rates, and calculation of disparities between groups.


https://dph.georgia.gov/cancer-reports

In [1]:
# Import the libraries
import numpy as np                  # Scientific Computing
import pandas as pd                 # Data Analysis
import matplotlib.pyplot as plt     # Plotting
import seaborn as sns               # Statistical Data Visualization

# Let's make sure pandas returns all the rows and columns for the dataframe
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Force pandas to display full numbers instead of scientific notation
# pd.options.display.float_format = '{:.0f}'.format

# Library to suppress warnings
import warnings
warnings.filterwarnings('ignore')

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
# Define the file path (adjust to your folder location)
file_path = "/content/drive/My Drive/Georgia_Cancer_Mortality.csv"

# Read the Excel file
ga_cancer = pd.read_csv(file_path)

In [7]:
# Display the first seven rows of the dataframe
ga_cancer.head(10)

,years,Region,BlackFemale_Deaths AllSites,WhiteFemale_Deaths AllSites,BlackFemale_Rate AllSites,WhiteFemale_Rate AllSites,BlackFemale_Deaths Colon,WhiteFemale_DeathsC,BlackFemale_Rate C,WhiteFemale_RateC,BlackFemale_Deaths L,WhiteFemale_DeathsL,BlackFemale_RateL,WhiteFemale_RateL,BlackFemale_DeathsB,WhiteFemale_DeathsB,BlackFemale_RateB,WhiteFemale_RateB
0,2016-2020,Georgia,12203,27853,138.7,127.0,1196.0,2335,13.8,10.8,2052,7142,23.5,31.7,2411,3933,26.5,18.4
1,2016-2020,Northwest,3153,2845,145.6,146.0,27.0,224,13.3,11.7,62,779,34.2,38.5,60,379,28.5,20.3
2,2016-2020,North Georgia,2031,1945,128.8,129.3,9.0,161,NaN,11.1,15,532,NaN,34.2,10,282,NaN,19.3
3,2016-2020,North,2888,2704,120.4,121.6,13.0,256,NaN,12.0,23,720,21.6,31.5,25,379,22.5,17.3
4,2016-2020,Cobb-Douglas,3069,2220,126.2,123.6,91.0,180,16.5,9.9,111,489,21.7,27.0,172,359,26.1,20.7
5,2016-2020,Fulton,3408,1404,119.4,98.0,190.0,114,15.0,7.9,335,302,26.0,21.4,382,215,28.4,15.0
6,2016-2020,Clayton,914,272,140.0,147.9,50.0,17,11.6,9.9,83,72,20.0,37.5,141,31,30.9,16.7
7,2016-2020,East Metro,3449,2167,125.9,125.0,92.0,184,13.4,10.6,133,500,19.9,28.6,221,354,26.3,20.5
8,2016-2020,DeKalb,2555,919,118.0,99.1,129.0,86,11.6,8.8,253,163,22.2,17.5,339,134,29.1,15.0
9,2016-2020,LaGrange,3619,2651,132.5,131.9,96.0,226,14.2,11.5,144,664,22.5,31.9,191,406,27.3,20.4

In [8]:
# Display the bottom seven rows of the dataframe
ga_cancer.tail(7)

,years,Region,BlackFemale_Deaths AllSites,WhiteFemale_Deaths AllSites,BlackFemale_Rate AllSites,WhiteFemale_Rate AllSites,BlackFemale_Deaths Colon,WhiteFemale_DeathsC,BlackFemale_Rate C,WhiteFemale_RateC,BlackFemale_Deaths L,WhiteFemale_DeathsL,BlackFemale_RateL,WhiteFemale_RateL,BlackFemale_DeathsB,WhiteFemale_DeathsB,BlackFemale_RateB,WhiteFemale_RateB
31,2020-2024,East Central,857,1358,132.4,137.0,96.0,107,15.3,11.1,148,332,22.6,32.1,135,180,20.9,18.9
32,2020-2024,West Central,731,944,141.4,132.4,66.0,86,12.8,12.7,120,242,22.3,32.2,126,130,25.2,19.5
33,2020-2024,South,298,738,124.1,125.0,26.0,58,10.7,10.1,44,157,17.8,25.1,48,108,20.6,19.2
34,2020-2024,Southwest,657,1073,136.5,136.2,48.0,91,10.2,12.1,90,258,17.4,31.5,113,117,24.8,15.0
35,2020-2024,Coastal,801,1845,135.0,125.6,66.0,146,11.3,10.4,117,455,19.1,29.6,154,243,26.1,17.2
36,2020-2024,Southeast,323,1375,139.4,148.9,37.0,123,16.2,14.0,52,339,21.7,35.0,65,186,27.6,20.5
37,2020-2024,Northeast,412,1871,141.4,129.5,49.0,165,16.7,11.6,66,420,21.6,27.8,54,254,19.2,18.0

In [9]:
ga_cancer.shape

(38, 18)

In [10]:
72531 * 147

10662057

In [12]:
# Clean column names
ga_cancer.columns = ga_cancer.columns.str.strip().str.lower().str.replace(" ", "_")

# Check missing values
ga_cancer.isnull().sum()

# Drop missing rows (if needed)
ga_cancer = ga_cancer.dropna()

# Preview cleaned data
ga_cancer.head(10)

,years,region,blackfemale_deaths_allsites,whitefemale_deaths_allsites,blackfemale_rate_allsites,whitefemale_rate_allsites,blackfemale_deaths_colon,whitefemale_deathsc,blackfemale_rate_c,whitefemale_ratec,blackfemale_deaths_l,whitefemale_deathsl,blackfemale_ratel,whitefemale_ratel,blackfemale_deathsb,whitefemale_deathsb,blackfemale_rateb,whitefemale_rateb
0,2016-2020,Georgia,12203,27853,138.7,127.0,1196.0,2335,13.8,10.8,2052,7142,23.5,31.7,2411,3933,26.5,18.4
1,2016-2020,Northwest,3153,2845,145.6,146.0,27.0,224,13.3,11.7,62,779,34.2,38.5,60,379,28.5,20.3
4,2016-2020,Cobb-Douglas,3069,2220,126.2,123.6,91.0,180,16.5,9.9,111,489,21.7,27.0,172,359,26.1,20.7
5,2016-2020,Fulton,3408,1404,119.4,98.0,190.0,114,15.0,7.9,335,302,26.0,21.4,382,215,28.4,15.0
6,2016-2020,Clayton,914,272,140.0,147.9,50.0,17,11.6,9.9,83,72,20.0,37.5,141,31,30.9,16.7
7,2016-2020,East Metro,3449,2167,125.9,125.0,92.0,184,13.4,10.6,133,500,19.9,28.6,221,354,26.3,20.5
8,2016-2020,DeKalb,2555,919,118.0,99.1,129.0,86,11.6,8.8,253,163,22.2,17.5,339,134,29.1,15.0
9,2016-2020,LaGrange,3619,2651,132.5,131.9,96.0,226,14.2,11.5,144,664,22.5,31.9,191,406,27.3,20.4
10,2016-2020,South Central,665,479,123.8,123.0,18.0,44,12.8,12.3,38,132,23.6,32.3,31,60,21.0,16.8
11,2016-2020,North Central,2353,1487,131.5,130.7,85.0,123,14.0,11.0,157,448,24.3,37.7,129,190,20.8,17.1

In [17]:
ga_cancer.columns

Index(['years', 'region', 'blackfemale_deaths_allsites',
       'whitefemale_deaths_allsites', 'blackfemale_rate_allsites',
       'whitefemale_rate_allsites', 'blackfemale_deaths_colon',
       'whitefemale_deathsc', 'blackfemale_rate_c', 'whitefemale_ratec',
       'blackfemale_deaths_l', 'whitefemale_deathsl', 'blackfemale_ratel',
       'whitefemale_ratel', 'blackfemale_deathsb', 'whitefemale_deathsb',
       'blackfemale_rateb', 'whitefemale_rateb'],
      dtype='object')

In [18]:
from scipy.stats import chi2_contingency

# Group deaths by time period
table = ga_cancer.groupby("years")[[
    "blackfemale_deaths_allsites",
    "whitefemale_deaths_allsites"
]].sum()

# Run chi-square test
chi2, p, dof, expected = chi2_contingency(table)

print("p-value:", p)

p-value: 0.0

In [20]:
# Create simple time order
ga_cancer["period_order"] = ga_cancer["years"].replace({
    ga_cancer["years"].unique()[0]: 1,
    ga_cancer["years"].unique()[1]: 2
})

from sklearn.linear_model import LinearRegression

X = ga_cancer[["period_order"]]
y_black = ga_cancer["blackfemale_rate_allsites"]

model = LinearRegression()
model.fit(X, y_black)

print("Trend (Black women):", model.coef_[0])

Trend (Black women): 1.4941176470588233